# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# set workdir
WORKDIR /app

# install dependencies
COPY pyproject.toml uv.lock ./
RUN pip install --no-cache-dir .

# copy source
COPY . .

# set unbuffered output for stdio
ENV PYTHONUNBUFFERED=1

# default command
CMD ["python", "ikb_mcp_server.py"]
